title: 'Jekyll and Tailwind CSS'
theme:
permalink: pretty
repository: andreif/github-pages-jekyll-tailwind

exclude:
  - README.md
  - vendor
  - node_modules
  - '*.config.js'
  - package*.json
  - .idea
  - Gemfile*
  - .github

plugins:
  - jekyll-redirect-from
  - jekyll-postcss

defaults:
  - scope:
      path: ''
    values:
      layout: default
