baseurl: ''
exclude:
  - README.md
  - vendor
  - node_modules
  - *.config.js
  - package*.json
  - assets
permalink: pretty
title: 'Jekyll and Tailwind CSS'

#theme: jekyll-theme-cayman

plugins:
  - jekyll-redirect-from
  - jekyll-postcss

defaults:
  - scope:
      path: ''
    values:
      layout: default
