title: 'Jekyll and Tailwind CSS'
theme:
permalink: pretty

exclude:
  - README.md
  - vendor
  - node_modules
  - '*.config.js'
  - package*.json
  - .idea
  - assets/css/tailwind.css
  - Gemfile*

plugins:
  - jekyll-redirect-from
  - jekyll-postcss

defaults:
  - scope:
      path: ''
    values:
      layout: default
