name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - run: pwd
#      - run: ls -la
#      - run: ls -la ..
#      - run: ls -la .git
#      - run: echo ${{ github.workspace }}
#      - run: git --version
#      - run: docker --version

      - run: make build-tailwind
      - run: make build-jekyll

#      - run: git status
#      - run: ls -la
#      - run: ls -la _site
      - run: git reset --hard
      - run: rm -rf assets
#      - run: git remote -v
#      - run: git fetch
#      - run: git branch -avv
      - run: git switch gh-pages
#      - run: ls -la
#      - run: ls -la _site
      - run: cp -r _site/* ./
#      - run: git status
      - run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
      - run: |
          git remote set-url origin git@github.com:andreif/github-pages-jekyll-tailwind.git
          git config --global user.name 'Github Actions'
          git config --global user.email 'github.actions@users.noreply.github.com'
          git commit -am "Deploy"
          git push

#      - name: Upload to GitHub Pages
#        uses: JamesIves/github-pages-deploy-action@releases/v3
#        with:
#            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#            BRANCH: gh-pages
##            FOLDER: site
