name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - run: pwd
      - run: ls -la
      - run: ls -la ..
      - run: ls -la .git
      - run: ls -la ${{ github.workspace }}

      - run: npm install

      - run: NODE_ENV=production npx tailwindcss -o assets/css/styles.css --minify

      - run: git --version
      - run: docker --version

      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
            -v ${{ github.workspace }}:/srv/jekyll \
            -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
            jekyll/builder:latest \
            /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - run: git status

#      - name: Upload to GitHub Pages
#        uses: JamesIves/github-pages-deploy-action@releases/v3
#        with:
#            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#            BRANCH: gh-pages
##            FOLDER: site
